---
- name: BUILDING THE AZURE NETWORK
  connection: local
  gather_facts: no
  hosts: all

  tasks:
  - name: CREATING VIRTUAL NETWORK
    azure_rm_virtualnetwork:
      name: "{{ my_vm_name }}"-VN
      state: present
      resource_group: MyResourceGroup
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      address_prefixes_cidr: "10.1.0.0/16"
      dns_servers: "8.8.8.8"

  - name: CREATING SUBNET
    azure_rm_subnet:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      name: "{{ my_vm_name }}"SN
      state: present
      virtual_network_name: "{{ my_vm_name }}"-VN
      resource_group: MyResourceGroup
      address_prefix_cidr: "10.1.19.0/24"
