- name: BUILDING THE AZURE NETWORK
  connection: local
  gather_facts: no
  hosts: all

  tasks:
    - name: CREATING VIRTUAL NETWORK
      azure_rm_virtualnetwork:
        subscription_id: “{{ my_subscription_id }}”
        client_id: “{{ my_client_id }}”
        secret: “{{ my_secret }}”
        tenant: “{{ my_tenant }}”
        name: ansiblepoc
        resource_group: MyResourceGroup
        address_prefixes_cidr: "10.1.0.0/16"
        dns_servers: "8.8.8.8"
        state: present

#    - name: DEBUG
#      debug:
#        msg: my_azure_ad_user: "{{ my_azure_ad_user }}" / my_azure_password: "{{ my_azure_password }}"
